image: elixir:latest

services:
  # - mysql:latest

# Préparation de l'environnement avant de pouvoir effectuer les tests
before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

# Lance les différents tests, et vérifie si tout est OK
release:
  tags:
    - docker
  script:
    - mix compile
    - mix credo -a --strict || echo '!! Need to improve code.'
    - mix test --cover
    - MIX_ENV=prod mix release
    - mv _build/prod/rel/network network
    - rm -rf network/releases
  artifacts:
    name: network
    paths:
      - network

# Permet de servir un site static avec la documentation
pages:
  tags:
    - docker
  script:
    - mix docs
    - mv doc public
  artifacts:
    paths:
      - public
